language: python

python:
  - 2.7

before_install:
  - git submodule update --init --recursive

install:
  - "pip install -Ur requirements.txt"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script: py.test -n 4 -v -r fsxXR --baseurl=https://affiliates.allizom.org --driver=firefox --destructive -m "not credentials"

env:
  - DISPLAY=':99.0'

notifications:
  email:
    - webqa-ci@mozilla.org
